@NormalApp_HostAddress = http://localhost:5013

### create

PUT {{NormalApp_HostAddress}}/api/comments
Accept: application/json
Content-Type: application/json
{
    "Content": "This is a test comment."
}

### detail

GET {{NormalApp_HostAddress}}/api/comments/1
Accept: application/json

### list

GET {{NormalApp_HostAddress}}/api/comments
Accept: application/json

### update
POST {{NormalApp_HostAddress}}/api/comments/1
Accept: application/json
Content-Type: application/json
{
    "Content": "This is a updated comment."
}

### delete
DELETE {{NormalApp_HostAddress}}/api/comments/1
