<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domians\CommentModel‌s\CommentModel‌s.csproj" />
    <ProjectReference Include="..\..\Domians\CommentServices\CommentServices.csproj" />
  </ItemGroup>

</Project>
